# Aditeya Srivastava (aditeys@clemson.edu)
# https://github.com/aditeyaS/8700-assignments/assignment-2

zoo:
	g++ Animal.cpp Zoo.cpp main.cpp -o zoo

clean:
	rm zoo outputfile

tarball:
	tar -czvf assignment2.tar.gz *.cpp *.h makefile inputfile